[program:smartsocket-mqtt]
process_name=%(program_name)s
command=/usr/bin/php /var/www/smartsocket/artisan mqtt:listen
directory=/var/www/smartsocket
user=www-data
autostart=true
autorestart=true
startsecs=5
startretries=10
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=20
redirect_stderr=true
stdout_logfile=/var/www/smartsocket/storage/logs/mqtt-supervisor.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=APP_ENV="production"
