[program:smartsocket-mqtt]
process_name=%(program_name)s
command=/usr/bin/php /www/wwwroot/smartsocket/smartsocketlaravel/artisan mqtt:listen
directory=/www/wwwroot/smartsocket/smartsocketlaravel
user=www-data
autostart=true
autorestart=true
startsecs=5
startretries=10
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=20
redirect_stderr=true
stdout_logfile=/www/wwwroot/smartsocket/smartsocketlaravel/storage/logs/mqtt-supervisor.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=APP_ENV="production"
